### ISSUE TITLE
Dynamic Graph Support for GPMA

### ISSUE THREAD

**Issue by nithinmanoj10** [bfGraph/Seastar#27]
In this issue we'll figure out how to run GPMA and integrate it with Seastar. All issues faced along the way will be documented here as well.

**Comment by JoelMathewC** [comment]
> How to define a GPMA
We can define a GPMA in the following format
```
    GPMA gpma;
    init_csr_gpma(gpma, node_size);
```
The is taken from [here](https://github.com/desert0616/gpma_demo/blob/45f3de8c62a2743fdac11bac5a40793179027ebb/gpma_demo.cu#L86)

The GPMA class is defined in `gpma.cuh` the `init_csr_gpma` can be found there as well.

> Inserting edges into a GPMA
They seem to have initialized the GPMA with the following function
```
update_gpma(gpma, base_keys, base_values);
```

**Comment by JoelMathewC** [comment]
Thrust Docs: https://docs.nvidia.com/cuda/thrust/index.html?highlight=host_vector#vectors
CUDA docs: https://nvidia.github.io/cuda-python/install.html

**Comment by nithinmanoj10** [comment]
# Possible fix to creating Python bindings for GPMA

Previously we had tried to create PyBind11 python bindings for the GPMA C++ module but in vain. We ran into multiple errors especially while compiling the CUDA and C++ files together. Tweaking the make files wasn't the best possible solution.

## PyTorch Tutorial for C++ Extensions in Python

Discovered this tutorial written by people at PyTorch to write custom LSTMs in C++/CUDA. They provide a step-by-step tutorial on how to integrate C++/CUDA modules with Python. The tutorial can be found [here](https://pytorch.org/tutorials/advanced/cpp_extension.html#writing-a-mixed-c-cuda-extension)

It is a very simple tutorial were they add C++ function wrappers over the CUDA kernels and we add PyBind function wrappers over these C++ functions instead. Also they are compiled and built together with a simple `setup.py` file provided by PyTorch.

```
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

setup(
    name='gpu_arithmetic',
    ext_modules=[
        CUDAExtension('gpu_arithmetic', [
            'gpu_arithmetic.cpp',
            'gpu_arithmetic_kernel.cu',
        ])
    ],
    cmdclass={
        'build_ext': BuildExtension
    })
```

We can also define a C++ class that can call methods that will call kernel functions. The C++ and CUDA codes should be in two different files and they should also have two different names.

## Sample Code

Here we are defining a C++ class names `NaturalRing` that has two attributes `a` and `b`. It has two methods named `add` and `mul`.

**gpu_arithmetic.cpp**
```
#include "stdio.h"
#include <pybind11/pybind11.h>

namespace py = pybind11;

int add_cuda(int a, int b);
int mul_cuda(int a, int b);

class NaturalRing
{
public:
    int a;
    int b;

    NaturalRing(int _a, int _b);
    int add();
    int mul();
};

NaturalRing::NaturalRing(int _a, int _b)
{
    a = _a;
    b = _b;
}

int NaturalRing::add()
{
    return add_cuda(a, b);
}

int NaturalRing::mul()
{
    return mul_cuda(a, b);
}

PYBIND11_MODULE(gpu_arithmetic, m)
{
    m.doc() = "CPython module to do basic arithmetic in the GPU"; // optional module docstring

    py::class_<NaturalRing>(m, "NaturalRing")
        .def(py::init<int, int>(), py::arg("_a"), py::arg("_b"))
        .def("add", &NaturalRing::add)
        .def("mul", &NaturalRing::mul)
        .def_readwrite("a", &NaturalRing::a)
        .def_readwrite("b", &NaturalRing::b);
}
```

The CUDA functions that are wrapped should be defined at the top of the C++ file. Here `add_cuda` and `mul_cuda` are the only wrapped functions. Then we add PyBindings for `NaturalRing`, like how we usually do it.

**gpu_arithmetic_kernel.cu**

```
__global__ void add(int *a, int *b, int *c)
{
    *c = *a + *b;
}

__global__ void mul(int *a, int *b, int *c)
{
    *c = *a * *b;
}

__host__ int add_cuda(int a, int b)
{
    int c; // result
    int *d_a, *d_b, *d_c;
    int size = sizeof(int);

    cudaMalloc((void **)&d_a, size);
    cudaMalloc((void **)&d_b, size);
    cudaMalloc((void **)&d_c, size);

    // Copy inputs to device
    cudaMemcpy(d_a, &a, size, cudaMemcpyHostToDevice);
    cudaMemcpy(d_b, &b, size, cudaMemcpyHostToDevice);

    // Launch add() kernel on GPU
    add<<<1, 1>>>(d_a, d_b, d_c);

    // Copy result back to host
    cudaMemcpy(&c, d_c, size, cudaMemcpyDeviceToHost);

    // Cleanup
    cudaFree(d_a);
    cudaFree(d_b);
    cudaFree(d_c);

    return c;
}

__host__ int mul_cuda(int a, int b)
{
    int c; // result
    int *d_a, *d_b, *d_c;
    int size = sizeof(int);

    cudaMalloc((void **)&d_a, size);
    cudaMalloc((void **)&d_b, size);
    cudaMalloc((void **)&d_c, size);

    // Copy inputs to device
    cudaMemcpy(d_a, &a, size, cudaMemcpyHostToDevice);
    cudaMemcpy(d_b, &b, size, cudaMemcpyHostToDevice);

    // Launch add() kernel on GPU
    mul<<<1, 1>>>(d_a, d_b, d_c);

    // Copy result back to host
    cudaMemcpy(&c, d_c, size, cudaMemcpyDeviceToHost);

    // Cleanup
    cudaFree(d_a);
    cudaFree(d_b);
    cudaFree(d_c);

    return c;
}
```
The kernel functions are written in a seperate `.cu` file.

## Building

We can build the `setup.py` file using the following command
```
python3 setup.py install
```
![image](https://user-images.githubusercontent.com/64126131/233830769-62747ec2-4067-4c2c-8629-e037cb7cdb26.png)

## Running

Before importing the custom library, we should make sure to always `import torch` before that, else there would be some linking errors.

**test.py**
```
import torch
from gpu_arithmetic import NaturalRing

help(NaturalRing)

n = NaturalRing(23, 45)

print(n.add())
print(n.mul())

**Output**

```

**Comment by JoelMathewC** [comment]
## Finally fixed

After quite a bit of work attempting to compile Python binded GPMA, we have finally found the fix. We tested out quite a few possibilities and landed on the most logical and easy way to compile the GPMA shared library and load it to python. The command is

```
nvcc $(python3 -m pybind11 --includes) -shared -rdc=true --compiler-options '-fPIC' -o gpma.so gpma.cu
```
